openapi: 3.0.0
info:
  title: Movie Quotes Updated API
  description: Api for Movie Quotes Updated
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: https://movie-quotes-back.guram-tsagareishvili.redberryinternship.ge/api
    description: production server

components:
  securitySchemes:
    Auth:      
      type: apiKey
      in: header       
      name: Authorization 
      description: Bearer {JWT token}

paths:  
  /login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1login"

  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"

  /logout:
      $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"

  /authorized-user:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1authorized-user"

  /google-login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1google-login"

  /forgot-password:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1forgot-password"

  /reset-password:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1reset-password"

  /email/verify/{id}/{hash}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1email"

  /secondary-email/verify/{id}/{hash}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1secondary-email"
    
  /movies:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies"
       
  /movies-all:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies-all"
    
  /movies/{movie}:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies-crud"
  
  /post:
    $ref: "./_swagger/paths/quotes.yaml#/paths/~1post"
              
  /search-post:
     $ref: "./_swagger/paths/quotes.yaml#/paths/~1search-post"
                  
  /quote/{quote}:
    $ref: "./_swagger/paths/quotes.yaml#/paths/~1quote-crud"
         
  /quote:
    $ref: "./_swagger/paths/quotes.yaml#/paths/~1quote"
  
  /likes:
    $ref: "./_swagger/paths/likes.yaml#/paths/~1likes"
             
  /likes/{like}:
    $ref: "./_swagger/paths/likes.yaml#/paths/~1likes-delete"
     
  /comment:
    $ref: "./_swagger/paths/comments.yaml#/paths/~1comment"
               
  /comment/{comment}:
    $ref: "./_swagger/paths/comments.yaml#/paths/~1comment-delete"
               
  /notifications:
    $ref: "./_swagger/paths/notifications.yaml#/paths/~1notifications"

  /categories:
    $ref: "./_swagger/paths/categories.yaml#/paths/~1categories"
              
  /name:
    $ref: "./_swagger/paths/user.yaml#/paths/~1name"
               
  /password:
    $ref: "./_swagger/paths/user.yaml#/paths/~1password"
               
  /add-email:
    $ref: "./_swagger/paths/user.yaml#/paths/~1add-email"
               
  /secondary-email:
    $ref: "./_swagger/paths/user.yaml#/paths/~1secondary-email"
               
  /make-primary:
    $ref: "./_swagger/paths/user.yaml#/paths/~1make-primary"
                
  /email:
    $ref: "./_swagger/paths/user.yaml#/paths/~1email"
                
  /profile-image:
    $ref: "./_swagger/paths/user.yaml#/paths/~1profile-image"
                

   